/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppProyeccionesRouteImport } from './routes/_app/proyecciones'
import { Route as AppPostCitaRouteImport } from './routes/_app/post-cita'
import { Route as AppListaEsperaRouteImport } from './routes/_app/lista-espera'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAnalisisRouteImport } from './routes/_app/analisis'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProyeccionesRoute = AppProyeccionesRouteImport.update({
  id: '/proyecciones',
  path: '/proyecciones',
  getParentRoute: () => AppRoute,
} as any)
const AppPostCitaRoute = AppPostCitaRouteImport.update({
  id: '/post-cita',
  path: '/post-cita',
  getParentRoute: () => AppRoute,
} as any)
const AppListaEsperaRoute = AppListaEsperaRouteImport.update({
  id: '/lista-espera',
  path: '/lista-espera',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalisisRoute = AppAnalisisRouteImport.update({
  id: '/analisis',
  path: '/analisis',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analisis': typeof AppAnalisisRoute
  '/dashboard': typeof AppDashboardRoute
  '/lista-espera': typeof AppListaEsperaRoute
  '/post-cita': typeof AppPostCitaRoute
  '/proyecciones': typeof AppProyeccionesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analisis': typeof AppAnalisisRoute
  '/dashboard': typeof AppDashboardRoute
  '/lista-espera': typeof AppListaEsperaRoute
  '/post-cita': typeof AppPostCitaRoute
  '/proyecciones': typeof AppProyeccionesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/analisis': typeof AppAnalisisRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/lista-espera': typeof AppListaEsperaRoute
  '/_app/post-cita': typeof AppPostCitaRoute
  '/_app/proyecciones': typeof AppProyeccionesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analisis'
    | '/dashboard'
    | '/lista-espera'
    | '/post-cita'
    | '/proyecciones'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analisis'
    | '/dashboard'
    | '/lista-espera'
    | '/post-cita'
    | '/proyecciones'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/analisis'
    | '/_app/dashboard'
    | '/_app/lista-espera'
    | '/_app/post-cita'
    | '/_app/proyecciones'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/proyecciones': {
      id: '/_app/proyecciones'
      path: '/proyecciones'
      fullPath: '/proyecciones'
      preLoaderRoute: typeof AppProyeccionesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/post-cita': {
      id: '/_app/post-cita'
      path: '/post-cita'
      fullPath: '/post-cita'
      preLoaderRoute: typeof AppPostCitaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lista-espera': {
      id: '/_app/lista-espera'
      path: '/lista-espera'
      fullPath: '/lista-espera'
      preLoaderRoute: typeof AppListaEsperaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analisis': {
      id: '/_app/analisis'
      path: '/analisis'
      fullPath: '/analisis'
      preLoaderRoute: typeof AppAnalisisRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalisisRoute: typeof AppAnalisisRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppListaEsperaRoute: typeof AppListaEsperaRoute
  AppPostCitaRoute: typeof AppPostCitaRoute
  AppProyeccionesRoute: typeof AppProyeccionesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalisisRoute: AppAnalisisRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppListaEsperaRoute: AppListaEsperaRoute,
  AppPostCitaRoute: AppPostCitaRoute,
  AppProyeccionesRoute: AppProyeccionesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
